public class calculatorController {
           @Auraenabled
    public static integer doAddition(integer firstNumber,integer secondNumber){
        return(firstNumber+secondNumber);
    }
    @Auraenabled
    public static integer doSubtraction(integer firstNumber,integer secondNumber){
        return(firstNumber-secondNumber);
    }
    @Auraenabled
    public static integer doDivision(integer firstNumber,integer secondNumber){
        return(firstNumber/secondNumber);
    }
    @Auraenabled
    public static integer doMultiplication(integer firstNumber,integer secondNumber){
        return(firstNumber*secondNumber);
    }
}